from pydantic import BaseModel
from typing import Optional

# Base schema with common attributes
class ItemBase(BaseModel):
    title: str
    description: Optional[str] = None

# Schema used for creating an item
class ItemCreate(ItemBase):
    pass

# Schema used for returning an item (includes the ID generated by the DB)
class ItemResponse(ItemBase):
    id: int
    productTypeID: str
    # Tells Pydantic to read data even if it's not a dict (like an ORM model)
    model_config = {"from_attributes": True}